name: speech-recognition
on: [push]
jobs:
  run:
    runs-on: [Ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7.6'
      - uses: iterative/setup-cml@v1
      - name: data-processing
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          
          # python tests/test_meta_data.py
          # cat metrics.txt >> report.md
          # cml-send-comment report.md
